### ISSUE TITLE
12-bit ADC

### ISSUE THREAD

**Issue by thijstriemstra** [stechio/arduino-ad-mux-lib#2]
ESP32 has a 12-bit adc (afaik) and returns values between 0 and 4095. Is this supported in e.g. `mux.read`?

**Comment by stechio** [comment]
Mux.read supports up to 15 bits (that is [0, 32767] range): are you experiencing any issue about that?

**Comment by thijstriemstra** [comment]
> are you experiencing any issue about that?

No I haven't tested yet (e.g. not read data, just compilation for now) on ESP32 but will this weekend, I'll update or close ticket then.

**Comment by thijstriemstra** [comment]
Confirmed when using ESP32 it returns between 0 and 4095, e.g.

```
channel: 0, data: 2363
channel: 1, data: 2363
channel: 2, data: 2733
channel: 3, data: 2705
channel: 4, data: 2175
channel: 5, data: 1807
channel: 6, data: 2199
channel: 7, data: 1762
```
