### ISSUE TITLE
[ESP32] error: 'analogWrite' was not declared in this scope

### ISSUE THREAD

**Issue by thijstriemstra** [stechio/arduino-ad-mux-lib#3]
When trying to compile this library for ESP32 using PlatformIO the following error occurs:

```
.pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.cpp: In member function 'int8_t Mux::write(uint8_t, int8_t)':
.pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.cpp:121:32: error: 'analogWrite' was not declared in this scope
     analogWrite(signalPin, data);
                                ^
```

platformio config:

```ini
[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino

lib_deps =
  Analog-Digital Multiplexers
```

**Comment by thijstriemstra** [comment]
There's a polyfill that could help: https://github.com/ERROPiX/ESP32_AnalogWrite

**Comment by thijstriemstra** [comment]
See pull request #4 for a fix.

**Comment by thijstriemstra** [comment]
It also redefines ANALOG and DISABLED..

```
.pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Defs.h:22:0: warning: "DISABLED" redefined
 #define DISABLED 0
 ^
In file included from /home/foo/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:53:0,
                 from /home/foo/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:35,
                 from .pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.h:20,
                 from .pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.cpp:17:
/home/foo/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:51:0: note: this is the location of the previous definition
 #define DISABLED  0x00
 ^

.pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Defs.h:19:0: warning: "ANALOG" redefined
 #define ANALOG 0
 ^
In file included from /home/foo/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:53:0,
                 from /home/foo/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:35,
                 from .pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.h:20,
                 from .pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.cpp:17:
/home/foo/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:48:0: note: this is the location of the previous definition
 #define ANALOG            0xC0
 ^
```

**Comment by stechio** [comment]
It seems like analogWrite support on ESP32 fell into an age-old conundrum... ;)

Thanks for reporting both of those issues and related fixes: I'm going to include them in next release (please be patient, it won't be an overnight process).

**Comment by thijstriemstra** [comment]
I'm also seeing weird results using a lolin32 board using some capacative moisture sensors. It's possibly related to fact I'm using a few pins that are input-only:

```
  ; 74HC4067 multiplexer
  -D MultiPlexerSignalPin=35
  -D MultiPlexerS0Pin=36
  -D MultiPlexerS1Pin=32
  -D MultiPlexerS2Pin=34
  -D MultiPlexerS3Pin=39
```

And https://randomnerdtutorials.com/esp32-pinout-reference-gpios/ states:

> GPIOs 34 to 39 are GPIs – input only pins. These pins don’t have internal pull-ups or pull-down resistors. 

Can I use those input-only pins? Seems not.. I will try some other pins (e.g. use 32 for signal and move S pins to something fully i/o.

**Comment by ketan** [comment]
I made the same mistake using GPIO 34-39 (since they are on the same side of the dev board I'm using) — using other pins seems to work fine.

**Comment by stechio** [comment]
Here we are: good news unfolding... :)

While the analogWrite fix was pretty straightforward, solving the name clash in a robust and durable manner required a compatibility break (enumerations+namespace). Therefore, _I have moved all the fixes relating to this issue to the [next major dev branch](https://github.com/stechio/arduino-ad-mux-lib/tree/feat/dev3)_. 

The new implementation is already available, so please get it a try and let me know (API has changed, so take care to tweak your code accordingly -- see updated README.md and examples).

**Comment by stechio** [comment]
Thanks @thijstriemstra for [your suggestion](https://github.com/stechio/arduino-ad-mux-lib/pull/5), now [dev 3 branch](https://github.com/stechio/arduino-ad-mux-lib/tree/feat/dev3) has Travis CI enabled.

[Passing multiple board builds via platformIO](https://travis-ci.com/github/stechio/arduino-ad-mux-lib/builds/177969068), the latest commits ([98b8104](https://github.com/stechio/arduino-ad-mux-lib/commit/98b81041abb8c0a78bf62940f9c4924e6c0b353b) and [28966f8](https://github.com/stechio/arduino-ad-mux-lib/commit/28966f88f64aceea001158b36aa092287aa1512a)) solved some lurking bugs and compatibility issues.

What do you think about the current implementation?

**Comment by thijstriemstra** [comment]
@stechio looks good to me.

**Comment by trylika** [comment]
Not to nag, but when new version is going to be released?
Coincidentally i'm trying to setup mux(HP4067) with esp32, if there is a need i could help with testing/writing.

**Comment by stechio** [comment]
Hi @trylika, I'm currently preparing unit tests (via [ArduinoFake](https://github.com/FabioBatSilva/ArduinoFake)); in the meantime, you can try the new version on the [next major dev branch](https://github.com/stechio/arduino-ad-mux-lib/tree/feat/dev3) as described in [my previous comment](https://github.com/stechio/arduino-ad-mux-lib/issues/3#issuecomment-665927242). Let me know if you have any doubt/suggestion, thanks.

**Comment by trylika** [comment]
@stechio i did try, and everything seems to be working, will be testing more later, but what i found missing is `INPUT_PULLDOWN` - some of boards (especially esp32) can do pulldown inputs, which currently is not possible in this library.
Personally i didn't use it, but it might be beneficial to add one.

Also i found a bit confusing with `writePin` mostly because i'm using simple `74HC4067` based chip, which only has `signalPin`

**Comment by stechio** [comment]
You are right: I have to add support to onboard pullup/pulldown inputs.

In my latest commit I purged `writePin` (it was an experimental extension -- better to keep the code as clean as possible).

**Comment by stechio** [comment]
Now onboard pullup/pulldown inputs are available too.

**Comment by trylika** [comment]
looks good! will tryout a bit later

**Comment by stechio** [comment]
Meanwhile, I revised the entire code base, consolidating each and every part (library sources, unit tests and examples).

If I don't receive any bug report by the end of next week, I will release version 3 in production.
Looking forward to your check, thanks guys!

**Comment by trylika** [comment]
just tested out, "works on my machine" :)

**Comment by stechio** [comment]
As you may have seen on your notifications, I'm glad to announce [version 3 was released today](https://github.com/stechio/arduino-ad-mux-lib/releases/tag/3.0.0).

Thanks to everyone contributing to its advancement, especially @thijstriemstra

**Comment by thijstriemstra** [comment]
cheers!
