### ISSUE TITLE
"Pin" conflicts with FastLED library

### ISSUE THREAD

**Issue by ignotus666** [stechio/arduino-ad-mux-lib#6]
If using this library and the FastLED library in a sketch, an error is thrown saying "Pin" is ambiguous in the initialisation declaration ("Pin" is also used by FastLED apparently). I got around it by changing "Pin" to "sigPin" in the library source files, but maybe I'm missing something and it can be done without changing anything in the source files?

**Comment by stechio** [comment]
As you suspected, the library's types are purposely wrapped inside their own namespace (`admux`) to avoid such name clashes. Therefore, in order to reference `Pin`, just prefix it this way:
```c++
admux::Pin
```

**Comment by ignotus666** [comment]
I had a feeling I was probably making a noob mistake. Thank you very much for the explanation and for the library, I've found it very useful!
